Shellcheck fixes

diff --git a/semtag b/semtag
--- a/semtag
+++ b/semtag
@@ -1,5 +1,22 @@
 #!/usr/bin/env bash
 
+# Enable xtrace if the DEBUG environment variable is set
+if [[ ${DEBUG-} =~ ^1|yes|true$ ]]; then
+    set -o xtrace       # Trace the execution of the script (debug)
+fi
+
+# set bash "strict mode"
+set -o errexit      # Exit on most errors (see the manual)
+set -o nounset      # Disallow expansion of unset variables
+set -o pipefail     # Use last non-zero exit code in a pipeline
+
+# utility function to print error to stderr
+echoerr() { printf "%s\n" "$*" >&2; }
+
+# utility function to print error and exit
+exiterr() { echoerr "$@" ; exit 1; }
+
+
 PROG=semtag
 PROG_VERSION="v0.1.2"
 
@@ -65,9 +82,10 @@ Commands:
                the commits from the last final version."
 
 # Commands and options
-ACTION="getlast"
-ACTION="$1"
-shift
+ACTION="${1:-getlast}"
+if [[ -n ${1:-} ]] ; then
+  shift
+fi
 
 # We get the parameters
 while getopts "v:s:ofp" opt; do
@@ -87,13 +105,11 @@ while getopts "v:s:ofp" opt; do
     p)
       prefix=""
       ;;
-    \?)
-      echo "Invalid option: -$OPTARG" >&2
-      exit 1
-      ;;
     :)
-      echo "Option -$OPTARG requires an argument." >&2
-      exit 1
+      exiterr "Option -$OPTARG requires an argument."
+      ;;
+    *)
+      exiterr "Invalid option: -$OPTARG"
       ;;
   esac
 done
@@ -103,11 +119,13 @@ done
 function get_default_branch {
   local __result=$1
 
-  local __remotes=$(git remote)
+  local __remotes
+  __remotes=$(git remote)
   if [[ -n $__remotes ]]; then
     for __remote in $__remotes; do
-      local __default_branch_ref=$(git symbolic-ref --quiet refs/remotes/${__remote}/HEAD || true)
-      local __default_branch=${__default_branch_ref#refs/remotes/${__remote}/}
+      local __default_branch_ref
+      __defautlt_branch_ref=$(git symbolic-ref --quiet refs/remotes/"${__remote}"/HEAD || true)
+      local __default_branch="${__default_branch_ref#refs/remotes/"${__remote}"/}"
       if [[ -n ${__default_branch} ]]; then
         break
       fi
@@ -147,16 +165,19 @@ function explode_version {
 function compare_versions {
   local __first
   local __second
-  explode_version $1 __first
-  explode_version $2 __second
+  explode_version "$1" __first
+  explode_version "$2" __second
   local lv=$3
 
   # Compares MAJOR, MINOR and PATCH
   for i in 0 1 2; do
     local __numberfirst=${__first[$i]}
     local __numbersecond=${__second[$i]}
-    case $(($__numberfirst - $__numbersecond)) in
+    local __comparison=$((__numberfirst - __numbersecond))
+    case $__comparison in
       0)
+        eval "$lv=0"
+        return 0
         ;;
       -[0-9]*)
         eval "$lv=-1"
@@ -165,6 +186,9 @@ function compare_versions {
       [0-9]*)
         eval "$lv=1"
         return 0
+        ;;
+      *)
+        exiterr "Unknown result: $__comparison"
         ;;
     esac
   done
@@ -223,7 +247,7 @@ function get_latest_of_two {
   local __result
   local __latest=$3
 
-  compare_versions $__first $__second __result
+  compare_versions "$__first" "$__second" __result
   case $__result in
     0)
       eval "$__latest=$__second"
@@ -233,6 +257,9 @@ function get_latest_of_two {
       ;;
     1)
       eval "$__latest=$__first"
+      ;;
+    *)
+      exiterr "Unknown result: $__result"
       ;;
   esac
 }
@@ -268,14 +295,14 @@ function compare_identifiers {
   local __result=$3
   local partresult
   local arraylengths
-  if [[ -n "$__first" ]] && [[ -n "$__second" ]]; then
+  if [[ -n $__first ]] && [[ -n $__second ]]; then
     explode_identifier "${__first}" explodedidentifierfirst
     explode_identifier "${__second}" explodedidentifiersecond
 
     firstsize=${#explodedidentifierfirst[@]}
     secondsize=${#explodedidentifiersecond[@]}
-    minlength=$(( $firstsize<$secondsize ? $firstsize : $secondsize ))
-    for (( i = 0 ; i < $minlength ; i++ )); do
+    minlength=$(( firstsize<secondsize ? firstsize : secondsize ))
+    for (( i = 0 ; i < minlength ; i++ )); do
       compare_identifier_part "${explodedidentifierfirst[$i]}" "${explodedidentifiersecond[$i]}" partresult
       case $partresult in
         0)
@@ -286,13 +313,13 @@ function compare_identifiers {
           ;;
       esac
     done
-    compare_numeric $firstsize $secondsize arraylengths
+    compare_numeric "$firstsize" "$secondsize" arraylengths
     eval "$__result=$arraylengths"
     return 0
-  elif [[ -z "$__first" ]] && [[ -n "$__second" ]]; then
+  elif [[ -z $__first ]] && [[ -n $__second ]]; then
     eval "$__result=1"
     return 0
-  elif [[ -n "$__first" ]] && [[ -z "$__second" ]]; then
+  elif [[ -n $__first ]] && [[ -z $__second ]]; then
     eval "$__result=-1"
     return 0
   fi
@@ -307,8 +334,8 @@ function explode_identifier {
   local __identifier=$1
   local __result=$2
   if [[ $__identifier =~ $IDENTIFIER_REGEX ]] ; then
-    IFS='-.' read -ra identifierparts <<< $__identifier
-    eval "$__result=( ${identifierparts[@]} )"
+    IFS='-.' read -ra identifierparts <<< "$__identifier"
+    eval "$__result=( ${identifierparts[#]} )"
   else
     eval "$__result="
   fi
@@ -328,9 +355,9 @@ function get_latest {
       ;;
     1)
       __current=${__taglist[0]}
-      explode_version $__current ver
-      if [ -n "$ver" ]; then
-        if [ -n "${ver[3]}" ]; then
+      explode_version "$__current" ver
+      if [[ -n $ver ]]; then
+        if [[ -n ${ver[3]} ]]; then
           finalversion=$FIRST_VERSION
         else
           finalversion=$__current
@@ -342,17 +369,17 @@ function get_latest {
       fi
       ;;
     *)
-      local __lastpos=$(($__tagsnumber-1))
+      local __lastpos=$((__tagsnumber-1))
       for i in $(seq 0 $__lastpos)
       do
         __current=${__taglist[i]}
-        explode_version ${__taglist[i]} ver
-        if [ -n "$ver" ]; then
-          if [ -z "${ver[3]}" ]; then
-            get_latest_of_two $finalversion $__current finalversion
-            get_latest_of_two $lastversion $finalversion lastversion
+        explode_version "${__taglist[i]}" ver
+        if [[ -n $ver ]]; then
+          if [[ -z ${ver[3]} ]]; then
+            get_latest_of_two "$finalversion" "$__current" finalversion
+            get_latest_of_two "$lastversion" "$finalversion" lastversion
           else
-            get_latest_of_two $lastversion $__current lastversion
+            get_latest_of_two "$lastversion" "$__current" lastversion
           fi
         fi
       done
@@ -375,20 +402,24 @@ function get_next_version {
   local __fromversion=$1
   local __scope=$2
   local __result=$3
-  explode_version $__fromversion __exploded
+  explode_version "$__fromversion" __exploded
   case $__scope in
     major)
-      __exploded[0]=$((${__exploded[0]}+1))
+      __exploded[0]=$((__exploded[0]+1))
       __exploded[1]=0
       __exploded[2]=0
     ;;
     minor)
-      __exploded[1]=$((${__exploded[1]}+1))
+      __exploded[1]=$((__exploded[1]+1))
       __exploded[2]=0
     ;;
     patch)
-      __exploded[2]=$((${__exploded[2]}+1))
+      __exploded[2]=$((__exploded[2]+1))
     ;;
+    *)
+      exiterr "Invalid scope: $__scope"
+      ;;
+
   esac
 
   eval "$__result=${prefix}${__exploded[0]}.${__exploded[1]}.${__exploded[2]}"
@@ -396,33 +427,33 @@ function get_next_version {
 
 function bump_version {
   ## First we try to get the next version based on the existing last one
-  if [ "$scope" == "auto" ]; then
+  if [[ $scope == "auto" ]]; then
     get_scope_auto scope
   fi
 
   local __candidatefromlast=$FIRST_VERSION
   local __explodedlast
-  explode_version $lastversion __explodedlast
-  if [[ -n "${__explodedlast[3]}" ]]; then
+  explode_version "$lastversion" __explodedlast
+  if [[ -n ${__explodedlast[3]} ]]; then
     # Last version is not final
     local __idlast
-    explode_identifier ${__explodedlast[3]} __idlast
+    explode_identifier "${__explodedlast[3]}" __idlast
 
     # We get the last, given the desired id based on the scope
     __candidatefromlast="${prefix}${__explodedlast[0]}.${__explodedlast[1]}.${__explodedlast[2]}"
     if [[ -n "$identifier" ]]; then
       local __nextid="$identifier.1"
-      if [ "$identifier" == "${__idlast[0]}" ]; then
+      if [[ $identifier == "${__idlast[0]}" ]]; then
         # We target the same identifier as the last so we increase one
-        __nextid="$identifier.$(( ${__idlast[1]}+1 ))"
+        __nextid="$identifier.$(( __idlast[1]+1 ))"
         __candidatefromlast="$__candidatefromlast-$__nextid"
       else
         # Different identifiers, we make sure we are assigning a higher identifier, if not, we increase the version
         __candidatefromlast="$__candidatefromlast-$__nextid"
         local __comparedwithlast
-        compare_versions $__candidatefromlast $lastversion __comparedwithlast
-        if [ "$__comparedwithlast" == -1 ]; then
-          get_next_version $__candidatefromlast $scope __candidatefromlast
+        compare_versions "$__candidatefromlast" "$lastversion" __comparedwithlast
+        if [[ $__comparedwithlast == -1 ]]; then
+          get_next_version "$__candidatefromlast" "$scope" __candidatefromlast
           __candidatefromlast="$__candidatefromlast-$__nextid"
         fi
       fi
@@ -431,7 +462,7 @@ function bump_version {
 
   # Then we try to get the version based on the latest final one
   local __candidatefromfinal=$FIRST_VERSION
-  get_next_version $finalversion $scope __candidatefromfinal
+  get_next_version "$finalversion" "$scope" __candidatefromfinal
   if [[ -n "$identifier" ]]; then
     __candidatefromfinal="$__candidatefromfinal-$identifier.1"
   fi
@@ -439,7 +470,7 @@ function bump_version {
   # Finally we compare both candidates
   local __resultversion
   local __result
-  compare_versions $__candidatefromlast $__candidatefromfinal __result
+  compare_versions "$__candidatefromlast" "$__candidatefromfinal" __result
   case $__result in
     0)
       __resultversion=$__candidatefromlast
@@ -450,6 +481,9 @@ function bump_version {
     1)
       __resultversion=$__candidatefromlast
       ;;
+    *)
+      exiterr "Invalid result version: $__resultversion"
+      ;;
   esac
 
   eval "$1=$__resultversion"
@@ -458,12 +492,12 @@ function bump_version {
 function increase_version {
   local __version=
 
-  if [ -z $forcedversion ]; then
+  if [[ -z $forcedversion ]]; then
     bump_version __version
   else
     if [[ $forcedversion =~ $SEMVER_REGEX ]] ; then
-      compare_versions $forcedversion $lastversion __result
-      if [ $__result -le 0 ]; then
+      compare_versions "$forcedversion" "$lastversion" __result
+      if [[ $__result -le 0 ]]; then
         echo "Version can't be lower than last version: $lastversion"
         exit 1
       fi
@@ -474,21 +508,21 @@ function increase_version {
     __version=$forcedversion
   fi
 
-  if [ "$displayonly" == "true" ]; then
+  if [[ $displayonly == "true" ]]; then
     echo "$__version"
   else
-    if [ "$forcetag" == "false" ]; then
+    if [[ $forcetag == "false" ]]; then
       check_git_dirty_status
     fi
     local __commitlist
-    if [ "$finalversion" == "$FIRST_VERSION" ] || [ "$hasversiontag" != "true" ]; then
+    if [[ $finalversion == "$FIRST_VERSION" ]] || [[ $hasversiontag != "true" ]]; then
       __commitlist="$(git log --pretty=oneline | cat)"
     else
-      __commitlist="$(git log --pretty=oneline $finalversion... | cat)"
+      __commitlist="$(git log --pretty=oneline "$finalversion..." | cat)"
     fi
 
     # If we are forcing a bump, we add bump to the commit list
-    if [[ -z $__commitlist && "$forcetag" == "true" ]]; then
+    if [[ -z $__commitlist && $forcetag == "true" ]]; then
       __commitlist="bump"
     fi
 
@@ -502,30 +536,28 @@ function increase_version {
 $__commitlist"
 
       # We check we have info on the user
-      local __username=$(git config user.name)
-      if [ -z "$__username" ]; then
+      local __username
+      __username=$(git config user.name)
+      if [[ -z $__username ]]; then
         __username=$(id -u -n)
-        git config user.name $__username
+        git config user.name "$__username"
       fi
-      local __useremail=$(git config user.email)
-      if [ -z "$__useremail" ]; then
+      local __useremail
+      __useremail=$(git config user.email)
+      if [[ -z $__useremail ]]; then
         __useremail=$(hostname)
         git config user.email "$__username@$__useremail"
       fi
 
-      git tag -a $__version -m "$__message"
+      git tag -a "$__version" -m "$__message"
 
       # If we have a remote, we push there
-      local __remotes=$(git remote)
+      local __remotes
+      __remotes=$(git remote)
       if [[ -n $__remotes ]]; then
         for __remote in $__remotes; do
-          git push $__remote $__version > /dev/null
-          if [ $? -eq 0 ]; then
-            echo "$__version pushed to $__remote"
-          else
-            echo "Error pushing the tag $__version to $__remote"
-            exit 1
-          fi
+          git push "$__remote" "$__version" > /dev/null
+          echo "$__version pushed to $__remote"
         done
       else
         echo "$__version"
@@ -538,14 +570,14 @@ function check_git_dirty_status {
   local __repostatus=
   get_work_tree_status __repostatus
 
-  if [ "$__repostatus" == "uncommitted" ]; then
-    echo "ERROR: You have uncommitted changes"
+  if [[ $__repostatus == "uncommitted" ]]; then
+    echoerr "ERROR: You have uncommitted changes"
     git status --porcelain
     exit 1
   fi
 
-  if [ "$__repostatus" == "unstaged" ]; then
-    echo "ERROR: You have unstaged changes"
+  if [[ $__repostatus == "unstaged" ]]; then
+    echoerr "ERROR: You have unstaged changes"
     git status --porcelain
     exit 1
   fi
@@ -553,18 +585,21 @@ function check_git_dirty_status {
 
 # Get the total amount of lines of code in the repo
 function get_total_lines {
-  local __empty_id="$(git hash-object -t tree /dev/null)"
-  local __changes="$(git diff --numstat $__empty_id | cat)"
-  local __added_deleted=$1
-  get_changed_lines "$__changes" $__added_deleted
+  local __empty_id
+  __empty_id="$(git hash-object -t tree /dev/null)"
+  local __changes
+  __changes="$(git diff --numstat "$__empty_id" | cat)"
+  local __added_deleted="$1"
+  get_changed_lines "$__changes" "$__added_deleted"
 }
 
 # Get the total amount of lines of code since the provided tag
 function get_sincetag_lines {
   local __sincetag=$1
-  local __changes="$(git diff --numstat $__sincetag | cat)"
+  local __changes
+  __changes="$(git diff --numstat "$__sincetag" | cat)"
   local __added_deleted=$2
-  get_changed_lines "$__changes" $__added_deleted
+  get_changed_lines "$__changes" "$__added_deleted"
 }
 
 function get_changed_lines {
@@ -580,8 +615,8 @@ function get_changed_lines {
     if [[ $i =~ $__diff_regex ]] ; then
       local __added=${BASH_REMATCH[1]}
       local __deleted=${BASH_REMATCH[2]}
-      __total_added=$(( $__total_added+$__added ))
-      __total_deleted=$(( $__total_deleted+$__deleted ))
+      __total_added=$(( __total_added+__added ))
+      __total_deleted=$(( __total_deleted+__deleted ))
     fi
   done
   eval "$2=( $__total_added $__total_deleted )"
@@ -594,12 +629,12 @@ function get_scope_auto {
   local __scope=
 
   get_total_lines __total
-  get_sincetag_lines $finalversion __since
+  get_sincetag_lines "$finalversion" __since
 
   local __percentage=0
-  if [ "$__total" != "0" ]; then
-    local __percentage=$(( 100*$__since/$__total ))
-    if [ $__percentage -gt "10" ]; then
+  if [[ $__total != "0" ]]; then
+    local __percentage=$(( 100*__since/__total ))
+    if [[ $__percentage -gt "10" ]]; then
       __scope="minor"
     else
       __scope="patch"
@@ -630,40 +665,43 @@ function get_work_tree_status {
 }
 
 function get_current {
-  if [ "$hasversiontag" == "true" ]; then
-    local __commitcount="$(git rev-list $lastversion.. --count)"
+  local __commitcount
+  if [[ $hasversiontag == "true" ]]; then
+    __commitcount="$(git rev-list "$lastversion.." --count)"
   else
-    local __commitcount="$(git rev-list --count HEAD)"
+    __commitcount="$(git rev-list --count HEAD)"
   fi
   local __status=
   get_work_tree_status __status
 
-  if [ "$__commitcount" == "0" ] && [ -z "$__status" ]; then
+  if [[ $__commitcount == "0" ]] && [[ -z $__status ]]; then
     eval "$1=$lastversion"
   else
-    local __buildinfo="$(git rev-parse --short HEAD)"
-    local __currentbranch="$(git rev-parse --abbrev-ref HEAD | cut -c1-$MAX_BRANCH_LENGTH)"
+    local __buildinfo
+    __buildinfo="$(git rev-parse --short HEAD)"
+    local __currentbranch
+    __currentbranch="$(git rev-parse --abbrev-ref HEAD | cut -c1-"$MAX_BRANCH_LENGTH")"
     get_default_branch default_branch
-    if [ "$__currentbranch" != "master" ]; then
+    if [[ $__currentbranch != "master" ]]; then
       __buildinfo="$__currentbranch.$__buildinfo"
     fi
 
     local __suffix=
-    if [ "$__commitcount" != "0" ]; then
-      if [ -n "$__suffix" ]; then
+    if [[ $__commitcount != "0" ]]; then
+      if [[ -n $__suffix ]]; then
         __suffix="$__suffix."
       fi
       __suffix="$__suffix$__commitcount"
     fi
-    if [ -n "$__status" ]; then
-      if [ -n "$__suffix" ]; then
+    if [[ -n $__status ]]; then
+      if [[ -n $__suffix ]]; then
         __suffix="$__suffix."
       fi
       __suffix="$__suffix$__status"
     fi
 
     __suffix="$__suffix+$__buildinfo"
-    if [ "$lastversion" == "$finalversion" ]; then
+    if [[ $lastversion == "$finalversion" ]]; then
       scope="patch"
       identifier=
       local __bumped=
@@ -677,9 +715,9 @@ function get_current {
 
 function init {
   TAGS="$(git tag --merged)"
-  IFS=$'\n' read -rd '' -a TAG_ARRAY <<<"$TAGS"
+  mapfile -t TAG_ARRAY <<<"$TAGS"
 
-  get_latest ${TAG_ARRAY[@]}
+  get_latest "${TAG_ARRAY[@]}"
   currentbranch="$(git rev-parse --abbrev-ref HEAD)"
 }
 
@@ -694,10 +732,9 @@ case $ACTION in
     init
     get_default_branch default_branch
     diff=$(git diff $default_branch | cat)
-    if [ "$forcetag" == "false" ]; then
-      if [ -n "$diff" ]; then
-        echo "ERROR: Branch must be updated with $default_branch for final versions"
-        exit 1
+    if [[ $forcetag == "false" ]]; then
+      if [[ -n $diff ]]; then
+        exiterr "ERROR: Branch must be updated with $default_branch for final versions"
       fi
     fi
     increase_version
@@ -731,6 +768,6 @@ case $ACTION in
     echo "Last tagged version:   $lastversion"
     ;;
   *)
-    echo "'$ACTION' is not a valid command, see --help for available commands."
+    echoerr "'$ACTION' is not a valid command, see --help for available commands."
     ;;
 esac
